version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: "phantom-panel-postgres"
    ports:
      - "127.0.0.1:9403:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: postgres

volumes: 
  postgres:
    name: "phantom-panel-postgres"
