// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Phantom.Controller.Database;

#nullable disable

namespace Phantom.Controller.Database.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221007095438_Instances")]
    partial class Instances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Phantom.Controller.Database.Entities.AgentEntity", b =>
                {
                    b.Property<Guid>("AgentGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxInstances")
                        .HasColumnType("integer");

                    b.Property<ushort>("MaxMemory")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AgentGuid");

                    b.ToTable("Agents", "agents");
                });

            modelBuilder.Entity("Phantom.Controller.Database.Entities.InstanceEntity", b =>
                {
                    b.Property<Guid>("InstanceGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JavaRuntimeGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("LaunchAutomatically")
                        .HasColumnType("boolean");

                    b.Property<ushort>("MemoryAllocation")
                        .HasColumnType("integer");

                    b.Property<string>("MinecraftServerKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinecraftVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RconPort")
                        .HasColumnType("integer");

                    b.Property<int>("ServerPort")
                        .HasColumnType("integer");

                    b.HasKey("InstanceGuid");

                    b.ToTable("Instances", "agents");
                });
#pragma warning restore 612, 618
        }
    }
}
